### ISSUE TITLE
act_5 "Cuadro comparativo"-Daisy Gonzalez Lita 

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Daisy-GonzalezLita12#1]
Actividad 5 cuadro comparativo "Tipos de textos"
Alumna: Daisy Gonzalez Lita
Grupo: 1BS
[Cuadro_Daisy_Gonzalez_Lita.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Daisy-GonzalezLita12/files/9623340/Cuadro_Daisy_Gonzalez_Lita.pdf)

**Comment by ErikCuevas03** [comment]
18,

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
