### ISSUE TITLE
Act. 5; Cuadro comparativo de textos, Emmanuel Marx Salazar González 1BS

### ISSUE THREAD

**Issue by marxgonzalez29** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Daisy-GonzalezLita12#2]
![TIPOS DE TEXTO](https://user-images.githubusercontent.com/112300981/194801437-5f6b4a2e-44d7-4c53-ad5d-b9a87fdda9fb.jpg)

**Comment by Jaczibeth** [comment]
Se tiene que volver a realizar ya que no cuenta con  los conceptos solicitados como es la nota periodística, etc. En caso de no realizarla tendrías 0% del 20%.

**Comment by josealfredo79** [comment]
solo agregar el concepto de nota periodistica

**Comment by josealfredo79** [comment]
por favor agregar el concepto de nota periodistica para tomar en cuenta

**Comment by marxgonzalez29** [comment]
![TIPOS DE TEXTO](https://user-images.githubusercontent.com/112300981/194801230-bd68e4ab-5ad1-46d9-a3fd-2d2a9a6d134c.jpg)

**Comment by josealfredo79** [comment]
Calificacion 15

**Comment by josealfredo79** [comment]
Revisado
